Section "InputClass"
        Identifier "libinput touchpad catchall"
        MatchIsTouchpad "on"
        MatchDevicePath "/dev/input/event*"
        Option "Tapping" "on"
        Option "ScrollMethod" "twofinger"
        Option "HorizontalScrolling" "on"
        Option "DisableWhileTyping" "on"
        Driver "libinput"
EndSection
